services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soaswag
    ports:
      - "5432:5432"
    volumes:
      - soaswag_pg:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - soaswag_redis:/data

  mailhog:
     image: mailhog/mailhog
     ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

volumes:
  soaswag_pg:
  soaswag_redis:
